### ISSUE TITLE
您好，请问下，如果键盘上出现了nodataView，如何去除？

### ISSUE THREAD

**Issue by fandongtongxue** [hanyx1992/XYTableViewNoDataView#1]
如题

**Comment by hanyx1992** [comment]
这个方案比较简单暴力, 目的是能最低成本的实现效果, 所以直接替换了所有的 UITableView, 可以修改一下源码对项目做适配. 比如项目使用 MVC 的话. tableView.delegate 一般都是 Controller, 可以判断 delegate 是 某个前缀. 或者是某个类的子类就不做处理,

例如:

``` objc
- (void)xy_havingData:(BOOL)havingData {
    //  不需要显示占位图
    if (![NSStringFromClass([self.delegate class]) hasPrefix:@"XY"] ) {
        [self freeNoDataViewIfNeeded];
        self.backgroundView = nil;
        return ;
    }

    ...
```

或者是如果项目内使用的都是 UITableView 的子类, 可以直接把 Category 加到对应子类中.

**Comment by fandongtongxue** [comment]
不好意思， 我可能没有表达好我的意思

**Comment by fandongtongxue** [comment]
[https://s3-cn-north-1.qiniucs.com/7ylqil/IMG_3825.PNG?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=JkFGFDvaJ2WDZlvPSnoiNDXUZEdXmbY8qnw7nMBh%2F20200715%2Fcn-north-1%2Fs3%2Faws4_request&X-Amz-Date=20200715T090800Z&X-Amz-Expires=360000&X-Amz-Signature=3111abdc2847a6c204aa9fe446e7e20d63a9e1a9057b7fb1aa1be3de2a5bdac1&X-Amz-SignedHeaders=host](url)

**Comment by fandongtongxue** [comment]
不好意思，文字不太好解释，麻烦复制链接，新建标签页打开

**Comment by fandongtongxue** [comment]
谢谢

**Comment by hanyx1992** [comment]
效率低可微信沟通 13803648899

**Comment by fandongtongxue** [comment]
解决了，谢谢大佬，很愉快的沟通
